language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  pip install -r dev_requirements.txt &&
  python dev_setup.py build_ext --inplace
# command to run tests
script: "py.test ."
