language: python
python:
  - "2.7"
  - "3.4"
  - "pypy"
  - "pypy3"
# command to install dependencies
#
install:
  - "pip install --upgrade setuptools"
  - "pip install preshed"
# command to run tests
script: "py.test tests/"
