language: python
matrix:
  include:
    - os: linux
      python: 3.5

    - os: osx
      sudo: required
      language: generic

install:
  - if [ "${TRAVIS_OS_NAME:-}" == "osx"]; then
      brew install python3;
    fi
  - pip install cython
  - pip3 install cibuildwheel==0.5.1
  - touch .cibuildwheel

script:
  - cibuildwheel --output-dir wheelhouse
